# Generated by Django 4.1.4 on 2023-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="product created at"
            ),
        ),
    ]
