# Generated by Django 4.1.4 on 2023-04-03 04:28

import api.product.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="product image name"),
                ),
                (
                    "alternative_text",
                    models.CharField(max_length=100, verbose_name="alternative text"),
                ),
                (
                    "product_image_url",
                    models.ImageField(
                        default="test.png",
                        upload_to=None,
                        verbose_name="product image url",
                    ),
                ),
                (
                    "order",
                    api.product.fields.OrderField(
                        blank=True, verbose_name="productline image order"
                    ),
                ),
                (
                    "productline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="product.productline",
                        verbose_name="product line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
    ]
