# Generated by Django 4.1.4 on 2023-05-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_product_type_productline_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="attribute_value",
            field=models.ManyToManyField(
                null=True,
                related_name="product_line_attribute_value",
                through="product.ProductLineAttributeValue",
                to="product.attributevalue",
                verbose_name="attribute value product line",
            ),
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attr_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_value_av",
                        to="product.attributevalue",
                        verbose_name="product attribute value",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_value_p",
                        to="product.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "unique_together": {("attr_value", "product")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="attribute_value",
            field=models.ManyToManyField(
                null=True,
                related_name="product_attribute_value",
                through="product.ProductAttributeValue",
                to="product.attributevalue",
                verbose_name="attribute value product line",
            ),
        ),
    ]
