# Generated by Django 4.1.4 on 2023-03-28 03:40

import api.product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="order",
            field=api.product.fields.OrderField(blank=True, null=True),
        ),
    ]
